name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: "adopt"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Ktlint
        run: ./gradlew ktlintCheck

      - name: Detekt
        run: ./gradlew detekt

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test